# -*- coding: utf-8 -*-
"""2021-1-ImgProc-HW2-Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DnFyaRSHNiUnOb9J_T_I5Y9xqOraWzn

### 2021-1 영상정보처리 2주차 과제
### - 마감: 3월 18일 11시 59분

<br><br>
다음의 셀에 구글 드라이브를 마운트하기 위한 명령어를 삽입하고 수행하시오
"""

from google.colab import drive
drive.mount('/gdrive')

"""다음의 셀에 현재 폴더 위치를 표시하는 명령어를 삽입하고 수행하시오"""

!pwd

"""다음의 셀에 템플리트 노트북 있는 폴더로 이동하고 해당 폴더에 속하는 파일/폴더를 보이는 명령어를 삽입하고 수행하시오."""

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/My Drive/Classroom/[영상정보처리] 2000004793-2021-1/2021-1 영상정보처리 2강/
# %ls

"""다음의 셀에 현재 폴더의 부모 폴더의 내용을 보여주는 명령어를 삽입하고 수행하시오. 보여지는 폴더에서 "Dongkeun-OpenCV-ImgData" 폴더가 없으면 드롭박스에서 해당 폴더를 다운로드하여 저장한 다음, 해당 폴더가 보일 때까지 수정하시오."""

# Commented out IPython magic to ensure Python compatibility.
# %ls ../

"""다음의 셀에 matplotlib.pyplot, cm, cv2 를 임포트하는 파이썬 코드를 삽입하시오.

이 다음 부터는 셀에 파이썬 코드를 삽입하면 수행하는 것은 자연스런 절차이므로 수행하라는 지시를 생략합니다.
"""

import matplotlib.pyplot as pyplot
import matplotlib.cm as cm
import cv2

"""다음의 셀에 위에서 확인한 이미지 데이터 폴더("../Dongkeun-OpenCV-ImgData")에 들어 있는 logo.png 파일을 읽고, type, size, dtype 를 출력하는 파이썬 코드를 삽입하시오."""

img = cv2.imread('../Dongkeun-OpenCV-ImgData/logo.png')

print('type = ', type(img))
print('size = ', img.size)
print('dtype = ', img.dtype)

"""다음의 셀이 입력된 이미지를 출력하는 파이썬 코드를 삽입하시오."""

pyplot.imshow(img)
pyplot.show()