# -*- coding: utf-8 -*-
"""2021-1-ImgProc-HW5-Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b00M7bIqs8m1NcIPfqe302tTWvDuWvUZ

## 2021-1 영상정보처리 5주차 과제 템플리트
- 점수: 10점 만점
- 이미지 경로 잘못 사용한 경우: -3
- 문제1: 5점 
- 문제2: 5점

이름: 황예진            
학번: 32195044

# 구글 드라이브 마우팅 및 작업 경로로 이동
- 다음 쉘에 필요한 작업을 하시오.
"""

from google.colab import drive 
drive.mount('/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/My Drive/Classroom/[영상정보처리] 2000004793-2021-1/2021-1 영상정보처리 5강/
import matplotlib.pyplot as plt
import numpy as np
import cv2

"""다음의 경로는 변경하지 말것"""

image_path = '../Dongkeun-OpenCV-ImgData/lena.jpg'

"""##문제 1:
a. 그레이스케일로 읽어온 영상을 flatten 시키고, shape 을 이용하여 확인하기
"""

## print function
def show_with_matplotlib(img, title):
  """Shows an image using matplotlib capabilities"""

  #Convert BGR image to RGB:
  img_RGB = img[:,:,::-1]
  
  #Show the image using matplotlib:
  plt.imshow(img_RGB)
  plt.title(title)
  plt.show()

def show_with_matplotlib_gray(img, title):
  plt.imshow(img, cmap="gray")
  plt.title(title)
  plt.show()

img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
print('img.shape=', img.shape)
show_with_matplotlib_gray(img, "Original Image")

img2 = img.flatten()
print('flattened img.shape=', img2.shape)

"""b. flatten 된 이미지를 3차원 shape 형태의 이미지로 바꾸고, 형태가 바뀐 이미지를 그레이스케일 이미지로 디스플레이하기."""

img3 = img.reshape(-1, 512, 512)
print('Reshapping to 3-dim, img.shape=', img3.shape)
show_with_matplotlib_gray(img3[0], "After reshaping")

"""##문제 2
위의 읽은 원래 이미지를 이용하여, y 축 방향으로 삼등분하여, 맨 윗쪽부터 각 하부영역 이미지를 Blue, Green, Red 성분만을 최대치로 변경한 이미지를 컬러이미지 형태로 디스프레이 하기. 
"""

img = cv2.imread(image_path)  ##read color image
img[0:170, :, 0] = 255  ##blue
img[170:340, :, 1] = 255  ##green
img[340:, :, 2] = 255  ##red
show_with_matplotlib(img, 'Color image with ROI')